pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}
// Esta es la forma moderna de reemplazar el bloque 'allprojects'.
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.name = "PortadasPeriodicos"
// ATENCIÓN: He eliminado el módulo ':sample'. Si realmente tienes ese módulo, vuelve a añadirlo.
include ':app'
